name: gitConfig
description: "Sets git username/email and push behavior"
runs:
  using: composite
  steps:
    - run: git config --global push.default current
      shell: bash
    - run: git config --global user.email svc_cli_bot@salesforce.com
      shell: bash
    - run: git config --global user.name svc-cli-bot
      shell: bash
