name: get prerelease tag
description: read package.json and return the version suffix (ex 'beta' if x.y.z-beta.0)

outputs:
  tag:
    value: ${{ steps.versionSuffix.outputs.prerelease }}
    description: version suffix (ex 'beta' if x.y.z-beta.0 ), if exists in package.json
  version:
    value: ${{ steps.packageVersion.outputs.prop }}
    description: version from pjson

runs:
  using: composite
  steps:
    - uses: notiz-dev/github-action-json-property@2192e246737701f108a4571462b76c75e7376216
      id: packageVersion
      with:
        path: "package.json"
        prop_path: "version"

    - run: echo "found version ${{ steps.packageVersion.outputs.prop  }}"
      shell: bash

    - uses: booxmedialtd/ws-action-parse-semver@e4a833cf5d612066a210bd9b62d1c3b20be3b325
      id: versionSuffix
      with:
        input_string: ${{ steps.packageVersion.outputs.prop }}

    - run: echo "found tag ${{ steps.versionSuffix.outputs.prerelease }}"
      shell: bash
