name: tag and github release
on:
  workflow_call:
    inputs:
      prerelease:
        type: boolean
        required: false
        default: false
        description: use a prerelease instead of a regular release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SF_CLI_BOT_GITHUB_TOKEN }}
      - name: Conventional Changelog Action
        id: changelog
        uses: salesforcecli/conventional-changelog-action@prereleases
        with:
          git-user-name: SF-CLI-BOT
          git-user-email: alm-cli@salesforce.com
          github-token: ${{ secrets.SF_CLI_BOT_GITHUB_TOKEN }}
          output-file: "false"
          tag-prefix: ""
      - name: Create Github Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.SF_CLI_BOT_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: ${{ inputs.prerelease }}
